import type { FormalityLevel } from "@/types/database";

export interface BotEntrySeed {
  japanese: string;
  translation: string;
  formality: FormalityLevel;
  tags: string[];
}

// A starter bank of common, everyday Japanese sentences — the kind a
// learner runs into constantly (greetings, convenience-store checkout,
// group-chat texting, anime/manga stock lines) but rarely sees with the
// pragmatic "why does it feel this way" context this board exists for.
// Posted by the bot account (see lib/bot-account.ts) so the board has real
// content to browse from day one instead of reading as empty.
export const BOT_ENTRY_SEEDS: BotEntrySeed[] = [
  { japanese: "お疲れ様です。", translation: "Thanks for your hard work.", formality: "Teineigo", tags: ["work", "greetings", "仕事"] },
  { japanese: "よろしくお願いします。", translation: "Please treat me well / I look forward to working with you.", formality: "Teineigo", tags: ["greetings", "business", "挨拶"] },
  { japanese: "お世話になっております。", translation: "Thank you for your continued support.", formality: "Teineigo", tags: ["business", "email", "ビジネス"] },
  { japanese: "少々お待ちください。", translation: "Please wait a moment.", formality: "Teineigo", tags: ["service", "business", "接客"] },
  { japanese: "申し訳ございません。", translation: "I'm terribly sorry.", formality: "Kenjougo", tags: ["apology", "business", "謝罪"] },
  { japanese: "かしこまりました。", translation: "Understood (formal, service context).", formality: "Kenjougo", tags: ["service", "business", "接客"] },
  { japanese: "失礼いたします。", translation: "Excuse me / pardon my intrusion.", formality: "Kenjougo", tags: ["greetings", "business", "挨拶"] },
  { japanese: "ご確認いただけますでしょうか。", translation: "Could you please check this?", formality: "Sonkeigo", tags: ["business", "email", "ビジネス"] },
  { japanese: "何かご不明な点はございますか。", translation: "Is there anything unclear?", formality: "Sonkeigo", tags: ["service", "business", "接客"] },
  { japanese: "先生がおっしゃった通りです。", translation: "It's exactly as the teacher said.", formality: "Sonkeigo", tags: ["school", "respect", "学校"] },
  { japanese: "袋はご利用ですか。", translation: "Would you like a bag?", formality: "Teineigo", tags: ["shopping", "convenience-store", "買い物"] },
  { japanese: "お会計、こちらでよろしいでしょうか。", translation: "Is this total okay with you?", formality: "Teineigo", tags: ["shopping", "convenience-store", "買い物"] },
  { japanese: "レジ袋は有料になります。", translation: "Plastic bags cost extra.", formality: "Teineigo", tags: ["shopping", "買い物"] },
  { japanese: "温めますか。", translation: "Would you like this heated up?", formality: "Teineigo", tags: ["convenience-store", "food", "コンビニ"] },
  { japanese: "ポイントカードはお持ちですか。", translation: "Do you have a point card?", formality: "Teineigo", tags: ["shopping", "買い物"] },
  { japanese: "了解！", translation: "Got it! (casual, common in group chats)", formality: "Casual", tags: ["texting", "chat", "メッセージ"] },
  { japanese: "マジで？", translation: "Seriously? / For real?", formality: "Casual", tags: ["texting", "reaction", "メッセージ"] },
  { japanese: "それな。", translation: "Right? / Exactly. (agreeing casually)", formality: "Slang", tags: ["texting", "chat", "メッセージ"] },
  { japanese: "草", translation: "lol (literally \"grass\" — from the kanji 笑 looking like grass when repeated)", formality: "Slang", tags: ["internet", "texting", "ネット用語"] },
  { japanese: "ワンチャンある。", translation: "There's a chance / it might just work out.", formality: "Slang", tags: ["internet", "chat", "ネット用語"] },
  { japanese: "詰んだ。", translation: "It's over / I'm doomed (lit. \"checkmated\").", formality: "Slang", tags: ["internet", "gaming", "ネット用語"] },
  { japanese: "びっくりした〜。", translation: "That startled me~", formality: "Casual", tags: ["reaction", "everyday", "リアクション"] },
  { japanese: "今行くね。", translation: "I'm heading over now.", formality: "Casual", tags: ["texting", "everyday", "メッセージ"] },
  { japanese: "全然大丈夫だよ。", translation: "It's totally fine.", formality: "Casual", tags: ["everyday", "reassurance", "日常"] },
  { japanese: "ちょっと待って！", translation: "Wait a sec!", formality: "Casual", tags: ["everyday", "日常"] },
  { japanese: "お腹すいた。", translation: "I'm hungry.", formality: "Casual", tags: ["everyday", "food", "日常"] },
  { japanese: "眠すぎる。", translation: "I'm way too sleepy.", formality: "Casual", tags: ["everyday", "日常"] },
  { japanese: "行くしかない。", translation: "There's no choice but to go.", formality: "Casual", tags: ["everyday", "determination", "日常"] },
  { japanese: "諦めるな！", translation: "Don't give up!", formality: "Casual", tags: ["anime", "encouragement", "アニメ"] },
  { japanese: "覚悟はいいか？", translation: "Are you ready? (lit. \"is your resolve ready\")", formality: "Casual", tags: ["anime", "dramatic", "アニメ"] },
  { japanese: "これで終わりだと思うなよ。", translation: "Don't think this is over.", formality: "Casual", tags: ["anime", "dramatic", "アニメ"] },
  { japanese: "お前を倒す！", translation: "I'll defeat you!", formality: "Casual", tags: ["anime", "battle", "アニメ"] },
  { japanese: "まだまだこれからだ。", translation: "This is just the beginning.", formality: "Casual", tags: ["anime", "determination", "アニメ"] },
  { japanese: "信じてたよ。", translation: "I believed in you.", formality: "Casual", tags: ["anime", "emotional", "アニメ"] },
  { japanese: "さすがだね。", translation: "As expected of you / impressive as always.", formality: "Casual", tags: ["compliment", "everyday", "褒め言葉"] },
  { japanese: "空気読んで。", translation: "Read the room. (lit. \"read the air\")", formality: "Casual", tags: ["idiom", "social", "慣用句"] },
  { japanese: "それは言わない約束でしょ。", translation: "We agreed not to bring that up, remember?", formality: "Casual", tags: ["everyday", "banter", "日常"] },
  { japanese: "そろそろ行かなきゃ。", translation: "I should get going soon.", formality: "Casual", tags: ["everyday", "日常"] },
  { japanese: "お先に失礼します。", translation: "Excuse me for leaving first (said when leaving work before coworkers).", formality: "Teineigo", tags: ["work", "greetings", "仕事"] },
  { japanese: "お疲れ〜！", translation: "Good work! (casual version of otsukaresama)", formality: "Casual", tags: ["work", "greetings", "仕事"] },
  { japanese: "本日も一日よろしくお願いいたします。", translation: "Thank you for your support again today.", formality: "Sonkeigo", tags: ["work", "morning", "仕事"] },
  { japanese: "だんだん寒くなってきましたね。", translation: "It's gradually getting colder, isn't it.", formality: "Teineigo", tags: ["small-talk", "weather", "世間話"] },
  { japanese: "お先にどうぞ。", translation: "After you.", formality: "Teineigo", tags: ["everyday", "manners", "日常"] },
  { japanese: "どういたしまして。", translation: "You're welcome.", formality: "Teineigo", tags: ["greetings", "everyday", "挨拶"] },
  { japanese: "お陰様で元気です。", translation: "Thanks to you, I'm doing well.", formality: "Teineigo", tags: ["greetings", "gratitude", "挨拶"] },
  { japanese: "たまげたわ。", translation: "That surprised me. (Kansai-flavored, casual)", formality: "Dialect", tags: ["kansai", "reaction", "関西弁"] },
  { japanese: "ほんまに？", translation: "Really? (Kansai dialect for \"honto ni\")", formality: "Dialect", tags: ["kansai", "reaction", "関西弁"] },
  { japanese: "なんでやねん！", translation: "Why on earth! (classic Kansai comedic retort)", formality: "Dialect", tags: ["kansai", "comedy", "関西弁"] },
  { japanese: "めっちゃ美味しい。", translation: "Really delicious. (めっちゃ = very, Kansai-origin but nationwide now)", formality: "Casual", tags: ["food", "everyday", "食べ物"] },

  // Second batch — added to extend the bank's runway. At the original
  // DEFAULT_BATCH (5/day) the first 47 entries exhausted in ~10 days,
  // after which the daily cron silently became a no-op forever (see the
  // "entry bank exhausted" branch in the seed route) — the board would
  // have quietly stopped getting any new bot content after its first
  // week and a half. This batch plus the slower cadence below buys
  // roughly a month of runway instead.
  { japanese: "承知いたしました。", translation: "Certainly, understood.", formality: "Kenjougo", tags: ["business", "email", "ビジネス"] },
  { japanese: "お手数をおかけします。", translation: "Sorry for the trouble.", formality: "Teineigo", tags: ["business", "apology", "ビジネス"] },
  { japanese: "ご確認のほど、よろしくお願いいたします。", translation: "Please kindly confirm at your convenience.", formality: "Sonkeigo", tags: ["business", "email", "ビジネス"] },
  { japanese: "恐れ入りますが。", translation: "Excuse me, but... (very polite preface before a request)", formality: "Kenjougo", tags: ["business", "service", "ビジネス"] },
  { japanese: "大変申し訳ございませんでした。", translation: "I am deeply sorry.", formality: "Kenjougo", tags: ["apology", "business", "謝罪"] },
  { japanese: "こちらでお召し上がりですか、お持ち帰りですか。", translation: "For here or to go?", formality: "Teineigo", tags: ["food", "service", "食べ物"] },
  { japanese: "少々お時間をいただきます。", translation: "This will take a little time.", formality: "Teineigo", tags: ["service", "接客"] },
  { japanese: "何名様ですか。", translation: "How many people in your party?", formality: "Teineigo", tags: ["restaurant", "service", "レストラン"] },
  { japanese: "お決まりでしたら、お伺いします。", translation: "I'll take your order whenever you're ready.", formality: "Teineigo", tags: ["restaurant", "service", "レストラン"] },
  { japanese: "いただきます。", translation: "Thanks for the meal (said before eating).", formality: "Teineigo", tags: ["food", "culture", "食べ物"] },
  { japanese: "ごちそうさまでした。", translation: "Thank you for the meal (said after eating).", formality: "Teineigo", tags: ["food", "culture", "食べ物"] },
  { japanese: "おかわりできますか。", translation: "Can I get a refill / seconds?", formality: "Teineigo", tags: ["food", "restaurant", "食べ物"] },
  { japanese: "辛いものは苦手です。", translation: "I'm not good with spicy food.", formality: "Teineigo", tags: ["food", "preference", "食べ物"] },
  { japanese: "既読スルーしないで。", translation: "Don't leave me on read.", formality: "Casual", tags: ["texting", "chat", "メッセージ"] },
  { japanese: "既読無視された。", translation: "They left me on read (ignored after reading).", formality: "Casual", tags: ["texting", "chat", "メッセージ"] },
  { japanese: "どゆこと？", translation: "What do you mean? (casual texting spelling of どういうこと)", formality: "Slang", tags: ["texting", "question", "メッセージ"] },
  { japanese: "りょ。", translation: "K. (super casual abbreviation of 了解)", formality: "Slang", tags: ["texting", "chat", "メッセージ"] },
  { japanese: "ガチで。", translation: "For real / seriously (casual intensifier).", formality: "Slang", tags: ["texting", "reaction", "メッセージ"] },
  { japanese: "推し活してる。", translation: "I'm doing fan activities for my favorite idol/character.", formality: "Casual", tags: ["internet", "fandom", "ネット用語"] },
  { japanese: "沼にハマった。", translation: "I've fallen deep into the hobby/fandom. (lit. \"stuck in a swamp\")", formality: "Slang", tags: ["internet", "fandom", "ネット用語"] },
  { japanese: "油断するな。", translation: "Don't let your guard down.", formality: "Casual", tags: ["anime", "warning", "アニメ"] },
  { japanese: "逃げちゃダメだ。", translation: "I mustn't run away.", formality: "Casual", tags: ["anime", "famous-line", "アニメ"] },
  { japanese: "本気を出す時が来た。", translation: "The time has come to go all out.", formality: "Casual", tags: ["anime", "battle", "アニメ"] },
  { japanese: "運命なんて信じない。", translation: "I don't believe in fate.", formality: "Casual", tags: ["anime", "dramatic", "アニメ"] },
  { japanese: "元気出して。", translation: "Cheer up.", formality: "Casual", tags: ["everyday", "comfort", "日常"] },
  { japanese: "無理しないでね。", translation: "Don't push yourself too hard, okay.", formality: "Casual", tags: ["everyday", "care", "日常"] },
  { japanese: "気にしないで。", translation: "Don't worry about it.", formality: "Casual", tags: ["everyday", "reassurance", "日常"] },
  { japanese: "どうしよう。", translation: "What should I do? (worried)", formality: "Casual", tags: ["everyday", "worry", "日常"] },
  { japanese: "なんとかなるよ。", translation: "It'll work out somehow.", formality: "Casual", tags: ["everyday", "reassurance", "日常"] },
  { japanese: "びみょう。", translation: "Meh / kind of iffy. (lit. \"subtle\")", formality: "Slang", tags: ["everyday", "opinion", "日常"] },
  { japanese: "テンション上がる！", translation: "This gets me hyped!", formality: "Casual", tags: ["everyday", "excitement", "日常"] },
  { japanese: "しんどい。", translation: "This is rough / I'm exhausted.", formality: "Casual", tags: ["everyday", "feeling", "日常"] },
  { japanese: "今日は暑いですね。", translation: "It's hot today, isn't it.", formality: "Teineigo", tags: ["small-talk", "weather", "世間話"] },
  { japanese: "台風が近づいているらしいです。", translation: "It seems a typhoon is approaching.", formality: "Teineigo", tags: ["weather", "news", "天気"] },
  { japanese: "花粉症がつらい。", translation: "My hay fever is rough.", formality: "Casual", tags: ["health", "seasonal", "健康"] },
  { japanese: "宿題やった？", translation: "Did you do your homework?", formality: "Casual", tags: ["school", "everyday", "学校"] },
  { japanese: "テスト勉強しなきゃ。", translation: "I have to study for the test.", formality: "Casual", tags: ["school", "everyday", "学校"] },
  { japanese: "先輩、お疲れ様です。", translation: "Good work, senpai.", formality: "Teineigo", tags: ["school", "respect", "学校"] },
  { japanese: "もしもし、聞こえますか。", translation: "Hello, can you hear me? (on the phone)", formality: "Teineigo", tags: ["phone", "everyday", "電話"] },
  { japanese: "今度飲みに行きましょう。", translation: "Let's go for drinks sometime.", formality: "Teineigo", tags: ["invitation", "social", "誘い"] },
  { japanese: "都合が良ければ。", translation: "If it's convenient for you.", formality: "Teineigo", tags: ["invitation", "business", "誘い"] },
  { japanese: "なんしよっと？", translation: "What are you doing? (Hakata/Fukuoka dialect)", formality: "Dialect", tags: ["hakata", "question", "博多弁"] },
  { japanese: "そうだべ？", translation: "Right? (Tohoku dialect for そうだろう)", formality: "Dialect", tags: ["tohoku", "agreement", "東北弁"] },
  { japanese: "なまら寒い。", translation: "Really cold. (Hokkaido dialect, なまら = \"very\")", formality: "Dialect", tags: ["hokkaido", "weather", "北海道弁"] },
  { japanese: "助かりました。", translation: "That really helped, thanks.", formality: "Teineigo", tags: ["gratitude", "everyday", "感謝"] },
  { japanese: "恩に着ます。", translation: "I owe you one. (formal gratitude)", formality: "Kenjougo", tags: ["gratitude", "感謝"] },
  { japanese: "ご迷惑をおかけしました。", translation: "I'm sorry for the trouble I caused.", formality: "Kenjougo", tags: ["apology", "business", "謝罪"] },
];
